# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# Use Node.js 20 Alpine as base image for smaller size
FROM node:20-alpine

# Set working directory
WORKDIR /app

# Copy package files
COPY package.json pnpm-lock.yaml ./

# Install pnpm globally
RUN npm install -g pnpm

# Install all dependencies (including dev deps for build)
# Note: Using --force instead of --frozen-lockfile for pnpm version compatibility
RUN pnpm install --force

# Accept git commit hash as build arg
ARG GIT_COMMIT=unknown

# Copy source code
COPY . .

# Build the application
RUN pnpm build

# Make git commit hash available at runtime and as image metadata
ENV GIT_COMMIT=$GIT_COMMIT
LABEL git-commit="$GIT_COMMIT"

# Remove dev dependencies to reduce image size
RUN pnpm prune --prod

# Expose the HTTP server port (configurable via PORT env var)
EXPOSE ${PORT:-3000}

# Set environment variables
ENV NODE_ENV=production

# Health check - use 127.0.0.1 to force IPv4 (server binds to 0.0.0.0)
HEALTHCHECK --interval=30s --timeout=3s --start-period=5s --retries=3 \
  CMD wget --no-verbose --tries=1 --spider http://127.0.0.1:${PORT:-3000}/health || exit 1

# Create non-root user for security
RUN addgroup -g 1001 -S nodejs && \
    adduser -S trademark -u 1001

# Change ownership of the app directory
RUN chown -R trademark:nodejs /app
USER trademark

# Start the HTTP server
# Environment variables are passed via docker-compose env_file or environment section
CMD ["node", "dist/server.js"]
